spring:
  application:
    name: study

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/paraglider?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    password: root
    username: root
server:
  port: 8899

# mybatis??
mybatis:
  # ???????
  typeAliasesPackage: com.mmm.study.entity
  # ??mapper?????????mapper.xml????
  mapperLocations: classpath:mapper/**/*.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.mmm.study.entity